import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

/**
 * Service Worker for high-performance request interception.
 * Serves game assets directly from the Origin Private File System (OPFS).
 */

// Precache all assets generated by Vite
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST || []);

const CACHE_NAME = "cadmium-shell-v9";
// Determine the base path for the Service Worker
const SW_BASE = self.location.pathname.substring(0, self.location.pathname.lastIndexOf('/') + 1);
const SANDBOX_PATH = SW_BASE + "vfs/";

self.addEventListener("install", (event) => {
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    Promise.all([
      self.clients.claim(),
      // Clear old caches
      caches.keys().then((keys) => {
        return Promise.all(
          keys.filter((key) => key !== CACHE_NAME && !key.includes('workbox')).map((key) => caches.delete(key))
        );
      }),
    ])
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);

  // Intercept requests to our local virtual file system path
  if (url.pathname.startsWith(SANDBOX_PATH)) {
    event.respondWith(handleGameAssetRequest(url, event.request));
    return;
  }
});

// Network-first strategy for the shell itself (for anything not precached)
registerRoute(
  ({ url, request }) => url.origin === self.location.origin && request.method === 'GET' && !url.pathname.startsWith(SANDBOX_PATH),
  new NetworkFirst({
    cacheName: CACHE_NAME,
  })
);

async function handleGameAssetRequest(url, request) {
  try {
    // Path format: /vfs/gameId/path/to/asset
    const relativePath = url.pathname.slice(SANDBOX_PATH.length);
    const pathParts = relativePath.split("/").filter(Boolean);
    
    if (pathParts.length < 1) {
      return new Response("Invalid VFS path", { status: 400 });
    }

    const gameId = decodeURIComponent(pathParts[0]);
    const filePath = decodeURIComponent(pathParts.slice(1).join("/") || "index.html");
    const subPaths = filePath.split("/");

    const root = await navigator.storage.getDirectory();
    if (!root) {
      return new Response("OPFS Root unavailable in Service Worker", { status: 500 });
    }
    
    let gameDir;
    let retryCount = 0;
    const maxRetries = 3;

    // Normalize gameId for matching: lowercase, replace non-alphanumeric with underscores, trim underscores
    const slugify = (s) => s.toLowerCase().replace(/[^a-z0-9]/gi, '_').replace(/^_+|_+$/g, '');
    const normalizedGameId = slugify(gameId);

    while (retryCount < maxRetries) {
      try {
        gameDir = await root.getDirectoryHandle(gameId);
        break; // Found it!
      } catch (e) {
        // Fallback search
        let found = false;
        const available = [];
        try {
          for await (const [name, handle] of root.entries()) {
            available.push(`${name} (${handle.kind})`);
            const normalizedName = slugify(name);
            
            if (handle.kind === 'directory' && (
                name.toLowerCase() === gameId.toLowerCase() || 
                normalizedName === normalizedGameId ||
                name === gameId + '.html' || 
                name + '.html' === gameId ||
                name.replace(/\s+/g, '_') === gameId.replace(/\s+/g, '_')
            )) {
              gameDir = handle;
              found = true;
              break;
            }
          }
        } catch (entriesError) {
          console.error("[SW] Error listing entries:", entriesError);
        }

        if (found) break;

        retryCount++;
        if (retryCount < maxRetries) {
          console.log(`[SW] Game ${gameId} (normalized: ${normalizedGameId}) not found, retrying (${retryCount}/${maxRetries})...`);
          await new Promise(r => setTimeout(r, 200 * retryCount));
        } else {
          const errorMsg = `Game directory not found: "${gameId}" (Normalized: "${normalizedGameId}"). 
            URL Path: ${url.pathname}
            Relative Path: ${relativePath}
            Path Parts: ${JSON.stringify(pathParts)}
            Available Entries: [${available.join(", ")}]
            Error: ${e.name} - ${e.message}`;
          
          return new Response(errorMsg, { 
            status: 404,
            headers: { "Content-Type": "text/plain" }
          });
        }
      }
    }

    let current;
    try {
      current = await gameDir.getDirectoryHandle("www");
    } catch (e) {
      return new Response(`Assets directory (www) not found for game: ${gameId}`, { status: 404 });
    }

    for (let i = 0; i < subPaths.length - 1; i++) {
      try {
        current = await current.getDirectoryHandle(subPaths[i]);
      } catch (e) {
        return new Response(`Directory not found: ${subPaths[i]} in path ${filePath}`, { status: 404 });
      }
    }

    let fileHandle;
    try {
      fileHandle = await current.getFileHandle(subPaths[subPaths.length - 1]);
    } catch (e) {
      return new Response(`File not found: ${subPaths[subPaths.length - 1]} in path ${filePath}`, { status: 404 });
    }
    const file = await fileHandle.getFile();

    // Determine MIME type
    let contentType = file.type;
    if (!contentType) {
      const ext = filePath.split('.').pop().toLowerCase();
      const mimeMap = {
        'js': 'application/javascript',
        'wasm': 'application/wasm',
        'html': 'text/html',
        'css': 'text/css',
        'json': 'application/json',
        'png': 'image/png',
        'jpg': 'image/jpeg',
        'jpeg': 'image/jpeg',
        'svg': 'image/svg+xml',
        'data': 'application/octet-stream',
        'txt': 'text/plain',
        'mp3': 'audio/mpeg',
        'wav': 'audio/wav',
        'ogg': 'audio/ogg',
        'mp4': 'video/mp4'
      };
      contentType = mimeMap[ext] || 'application/octet-stream';
    }

    const reqHeaders = request.headers;
    const rangeHeader = reqHeaders.get('Range');

    if (rangeHeader) {
      const bytesMatch = rangeHeader.match(/bytes=(\d+)-(\d*)/);
      if (bytesMatch) {
        const start = parseInt(bytesMatch[1], 10);
        const end = bytesMatch[2] ? parseInt(bytesMatch[2], 10) : file.size - 1;
        const chunkSize = end - start + 1;
        const slicedFile = file.slice(start, end + 1, contentType);

        return new Response(slicedFile, {
          status: 206,
          headers: {
            "Content-Type": contentType,
            "Content-Range": `bytes ${start}-${end}/${file.size}`,
            "Content-Length": chunkSize.toString(),
            "Accept-Ranges": "bytes",
            "Access-Control-Allow-Origin": "*",
            "Cache-Control": "public, max-age=3600",
            "Cross-Origin-Resource-Policy": "cross-origin",
            "X-Content-Type-Options": "nosniff",
            "Cross-Origin-Embedder-Policy": "credentialless",
            "Cross-Origin-Opener-Policy": "same-origin"
          }
        });
      }
    }

    return new Response(file, {
      headers: {
        "Content-Type": contentType,
        "Accept-Ranges": "bytes",
        "Access-Control-Allow-Origin": "*",
        "Cache-Control": "public, max-age=3600",
        "Cross-Origin-Resource-Policy": "cross-origin",
        "X-Content-Type-Options": "nosniff",
        "Cross-Origin-Embedder-Policy": "credentialless",
        "Cross-Origin-Opener-Policy": "same-origin"
      },
    });
  } catch (error) {
    return new Response(`Asset not found in VFS: ${url.pathname}`, { 
      status: 404,
      headers: { "Content-Type": "text/plain" }
    });
  }
}
